# Prometheus配置文件 - 部门地图系统 v3.1.0

global:
  # 全局抓取间隔
  scrape_interval: 15s
  # 全局评估间隔
  evaluation_interval: 15s
  # 外部标签
  external_labels:
    monitor: 'department-map-monitor'
    environment: 'production'
    version: 'v3.1.0'

# 规则文件配置
rule_files:
  - "rules/*.yml"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # 主应用监控
  - job_name: 'department-map-app'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: app:3000
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
      - source_labels: [__name__]
        regex: 'process_.*'
        action: drop

  # WebSocket服务监控
  - job_name: 'websocket-service'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 15s
    metrics_path: /ws/metrics
    scrape_timeout: 10s
    
  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics
    params:
      auth_module: [postgres]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: postgres-exporter:9187

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    scrape_interval: 30s
    metrics_path: /nginx_status
    params:
      format: ['prometheus']
    
  # Node Exporter监控（系统指标）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # cAdvisor监控（容器指标）
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # 自定义业务指标
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/business
    scrape_timeout: 15s
    params:
      module: [business]
    
  # 健康检查监控
  - job_name: 'health-check'
    static_configs:
      - targets: 
        - 'app:3000'
        - 'postgres:5432'
        - 'redis:6379'
    scrape_interval: 30s
    metrics_path: /health
    scrape_timeout: 5s
    
  # API性能监控
  - job_name: 'api-performance'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics/performance
    scrape_timeout: 10s
    
  # 用户会话监控
  - job_name: 'user-sessions'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/sessions
    scrape_timeout: 10s
    
  # 数据库连接池监控
  - job_name: 'db-pool'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics/db-pool
    scrape_timeout: 10s
    
  # WebSocket连接监控
  - job_name: 'websocket-connections'
    static_configs:
      - targets: ['app:8080']
    scrape_interval: 30s
    metrics_path: /ws/metrics/connections
    scrape_timeout: 10s
    
  # 缓存性能监控
  - job_name: 'cache-performance'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/cache
    scrape_timeout: 10s
    
  # 错误率监控
  - job_name: 'error-rates'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 30s
    metrics_path: /api/metrics/errors
    scrape_timeout: 10s
    
  # 安全事件监控
  - job_name: 'security-events'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 60s
    metrics_path: /api/metrics/security
    scrape_timeout: 10s
    
  # 文件上传监控
  - job_name: 'file-uploads'
    static_configs:
      - targets: ['app:3000']
    scrape_interval: 120s
    metrics_path: /api/metrics/uploads
    scrape_timeout: 15s

# 远程写入配置（可选）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'expensive_metric.*'
#         action: drop

# 远程读取配置（可选）
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint/api/v1/read"
#     basic_auth:
#       username: "username"
#       password: "password"

# 存储配置
storage:
  tsdb:
    # 数据保留时间
    retention.time: 30d
    # 数据保留大小
    retention.size: 10GB
    # 压缩级别
    wal-compression: true
    # 最小块持续时间
    min-block-duration: 2h
    # 最大块持续时间
    max-block-duration: 25h

# 查询配置
query:
  # 查询超时时间
  timeout: 2m
  # 最大并发查询数
  max-concurrency: 20
  # 最大样本数
  max-samples: 50000000
  # 查询日志文件
  log-queries-longer-than: 10s

# Web配置
web:
  # 监听地址
  listen-address: 0.0.0.0:9090
  # 外部URL
  external-url: http://localhost:9090
  # 路由前缀
  route-prefix: /
  # 启用生命周期API
  enable-lifecycle: true
  # 启用管理API
  enable-admin-api: true
  # 控制台模板目录
  console.templates: /etc/prometheus/consoles
  # 控制台库目录
  console.libraries: /etc/prometheus/console_libraries

# 日志配置
log:
  # 日志级别
  level: info
  # 日志格式
  format: logfmt

# 运行时配置
runtime:
  # GOMAXPROCS
  gomaxprocs: 4
  # 内存限制
  memory.limit: 2GB