# Prometheus测试环境配置
# 用于监控Docker容器资源使用情况

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'test'
    project: 'department-map'

# 规则文件
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 抓取配置
scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # API服务监控
  - job_name: 'api-service'
    static_configs:
      - targets: ['api-test:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Redis监控 (如果有Redis Exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-test:6379']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # PostgreSQL监控 (如果有Postgres Exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-test:5432']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Docker容器监控 (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# 远程写入配置 (可选)
# remote_write:
#   - url: "http://remote-storage:9201/write"

# 远程读取配置 (可选)  
# remote_read:
#   - url: "http://remote-storage:9201/read"